name: wordgame
description: A new Flutter project.
publish_to: 'none' #version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  generate: true
  
  assets:
    #- assets/dictionary.txt 
    - assets/words_en.json
    - assets/words_tr.json
